name: flutter_io_dev_tools

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.0.2
  code_excerpt_updater:
    path: site-shared/packages/code_excerpt_updater
  code_excerpter:
    path: site-shared/packages/code_excerpter
  linkcheck: ^2.0.6
  yaml: ^3.1.0
  path: ^1.6.2
  github: ^8.1.0
  firebase: ^9.0.1
