name: delete_data
description: Delete Data

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
